import type { LucideIcon } from 'lucide-react';
import { Bike, Footprints, Mountain, PersonStanding, Waves, Dumbbell, HeartPulse, Snowflake, Sailboat, Goal, Activity, CircleDot, Shield, StretchHorizontal, Zap } from 'lucide-react';

export type FocusId='bjj'|'running'|'cycling'|'yoga'|'judo'|'karate'|'swimming'|'hiking'|'climbing'|'crossfit'|'strength'|'walking'|'pilates'|'rowing'|'triathlon'|'soccer'|'basketball'|'tennis'|'dance'|'skiing'|'mobility'|'boxing';
export type FocusStatus='active'|'coming-soon';
export type FocusDefinition={id:FocusId;name:string;shortName:string;status:FocusStatus;route?:string;icon:LucideIcon;description:string;concept?:string;track?:string;connection?:string};

export const focusRegistry:FocusDefinition[]=[
 {id:'bjj',name:'Brazilian Jiu-Jitsu',shortName:'BJJ',status:'active',route:'BJJ',icon:PersonStanding,description:'Mat time, technical development, My Game and competition preparation.',concept:'Brazilian Jiu-Jitsu is a grappling practice built around positional control, escapes, transitions and submissions. Progress often comes from developing reliable decisions under resistance.',track:'Mat sessions, positional sparring, technique mastery, competition results and My Game pathways.',connection:'Use technical and competition goals to guide mat time, recovery and skill development.'},
 {id:'running',name:'Running',shortName:'Running',status:'active',route:'Running',icon:Footprints,description:'Runs, volume and lightweight performance context.',concept:'Running develops aerobic capacity, speed and endurance through a mix of easy mileage, structured workouts and recovery.',track:'Distance, pace, time, weekly volume, effort and race results.',connection:'Set a race or consistency goal, schedule runs and compare completed work with your plan.'},
 {id:'cycling',name:'Cycling',shortName:'Cycling',status:'active',route:'Cycling',icon:Bike,description:'Rides, volume and lightweight performance context.',concept:'Cycling builds endurance and leg capacity on roads, trails or indoor trainers, with room for both exploration and structured training.',track:'Distance, duration, elevation, power, cadence and ride effort.',connection:'Link rides to event or performance goals and balance them against other training demands.'},
 {id:'yoga',name:'Yoga',shortName:'Yoga',status:'coming-soon',icon:PersonStanding,description:'Movement, breath and deliberate practice.',concept:'Yoga combines movement, breath, balance and attention. The practice can be restorative, physically demanding, or both.',track:'Sessions, style, duration, mobility and consistency.',connection:'Build a weekly practice goal, schedule sessions and reflect on how they support recovery.'},
 {id:'judo',name:'Judo',shortName:'Judo',status:'coming-soon',icon:PersonStanding,description:'Throws, grips and controlled transitions.',concept:'Judo develops balance-breaking, throws, pins and movement under resistance.',track:'Mat sessions, technical themes, randori and competition.',connection:'Connect technical goals to scheduled practice and competition milestones.'},
 {id:'karate',name:'Karate',shortName:'Karate',status:'coming-soon',icon:PersonStanding,description:'Striking, forms and disciplined progression.',concept:'Karate develops distance, timing, striking mechanics and deliberate repetition through drills, kata and sparring.',track:'Classes, kata practice, sparring and rank milestones.',connection:'Organize skill-development goals and regular practice.'},
 {id:'swimming',name:'Swimming',shortName:'Swimming',status:'coming-soon',icon:Waves,description:'Technique, endurance and time in the water.',concept:'Swimming blends efficient technique with aerobic fitness and can serve as both primary training and cross-training.',track:'Distance, duration, pace, stroke and sessions.',connection:'Set distance or consistency goals and plan pool sessions.'},
 {id:'hiking',name:'Hiking',shortName:'Hiking',status:'coming-soon',icon:Mountain,description:'Trails, elevation and outdoor endurance.',concept:'Hiking combines sustained movement with terrain, elevation and time outdoors, from short local walks to demanding mountain days.',track:'Trail distance, elevation gain, duration and outings.',connection:'Plan hikes and build toward an endurance or destination goal.'},
 {id:'climbing',name:'Climbing',shortName:'Climbing',status:'coming-soon',icon:Mountain,description:'Strength, movement and problem-solving.',concept:'Climbing develops grip strength, technique, balance and route-reading across indoor and outdoor challenges.',track:'Sessions, grades, routes and projects.',connection:'Track a route project or grade milestone alongside strength and recovery.'},
 {id:'crossfit',name:'CrossFit',shortName:'CrossFit',status:'coming-soon',icon:PersonStanding,description:'Mixed-modal conditioning and strength.',concept:'CrossFit-style training combines strength, gymnastics and conditioning in varied sessions; scaling and recovery matter.',track:'Workouts, benchmark results, lifts and effort.',connection:'Tie benchmark goals to sessions and monitor training demands.'},
 {id:'strength',name:'Strength',shortName:'Strength',status:'coming-soon',icon:Dumbbell,description:'Build strength with deliberate progression.',concept:'Strength training develops force and movement capacity through progressive resistance work.',track:'Exercises, sets, reps, loads and personal bests.',connection:'Link lifts and programs to measurable strength goals.'},
 {id:'walking',name:'Walking',shortName:'Walking',status:'coming-soon',icon:Footprints,description:'Accessible daily movement and consistency.',concept:'Walking can anchor sustainable aerobic activity, recovery and outdoor time without requiring complex programming.',track:'Walks, steps, distance and minutes.',connection:'Create a movement habit and schedule manageable walks.'},
 {id:'pilates',name:'Pilates',shortName:'Pilates',status:'coming-soon',icon:StretchHorizontal,description:'Core control and coordinated movement.',concept:'Pilates emphasizes controlled movement, breathing, posture and trunk stability using mat or equipment-based exercises.',track:'Sessions, duration, movement progressions and consistency.',connection:'Support posture and movement-quality goals with regular practice.'},
 {id:'rowing',name:'Rowing',shortName:'Rowing',status:'coming-soon',icon:Sailboat,description:'Full-body aerobic and power training.',concept:'Rowing combines leg drive, trunk coordination and pulling in an endurance sport practiced on water or an ergometer.',track:'Distance, splits, duration and stroke rate.',connection:'Build toward a distance, pace or race target.'},
 {id:'triathlon',name:'Triathlon',shortName:'Triathlon',status:'coming-soon',icon:Activity,description:'Integrate swimming, cycling and running.',concept:'Triathlon training balances three endurance disciplines, transitions and recovery rather than maximizing one sport alone.',track:'Swims, rides, runs, bricks and race preparation.',connection:'Connect multi-sport scheduling to a single event goal.'},
 {id:'soccer',name:'Soccer',shortName:'Soccer',status:'coming-soon',icon:Goal,description:'Team play, agility and match fitness.',concept:'Soccer mixes skill, tactical awareness, repeated running efforts and coordinated team play.',track:'Training, matches, minutes and skill work.',connection:'Plan practices and connect consistency to performance objectives.'},
 {id:'basketball',name:'Basketball',shortName:'Basketball',status:'coming-soon',icon:CircleDot,description:'Court skills, movement and game readiness.',concept:'Basketball develops shooting, footwork, conditioning and decision-making in a fast team setting.',track:'Practices, games, shooting drills and minutes.',connection:'Build skill or consistency goals around court time.'},
 {id:'tennis',name:'Tennis',shortName:'Tennis',status:'coming-soon',icon:CircleDot,description:'Racket skills, movement and match play.',concept:'Tennis combines stroke mechanics, footwork, strategy and repeated bursts of movement.',track:'Court sessions, matches, drills and practice time.',connection:'Schedule practice and track progress toward match goals.'},
 {id:'dance',name:'Dance',shortName:'Dance',status:'coming-soon',icon:Zap,description:'Rhythm, coordination and expressive movement.',concept:'Dance can be creative practice, athletic training or social movement across many styles.',track:'Classes, rehearsals, duration and routines.',connection:'Plan practice toward a performance or consistency goal.'},
 {id:'skiing',name:'Skiing',shortName:'Skiing',status:'coming-soon',icon:Snowflake,description:'Snow sport technique and mountain endurance.',concept:'Skiing blends terrain reading, balance, leg endurance and technical progression on snow.',track:'Ski days, runs, vertical distance and lessons.',connection:'Plan seasonal trips and skill milestones.'},
 {id:'mobility',name:'Mobility',shortName:'Mobility',status:'coming-soon',icon:HeartPulse,description:'Move more freely and intentionally.',concept:'Mobility practice develops usable range of motion and control through targeted exercises.',track:'Sessions, targeted joints, duration and range benchmarks.',connection:'Support training readiness and movement-quality goals.'},
 {id:'boxing',name:'Boxing',shortName:'Boxing',status:'coming-soon',icon:Shield,description:'Footwork, striking and conditioning.',concept:'Boxing develops timing, distance, defense and efficient punches through drills, bag work and sparring.',track:'Rounds, classes, skill themes and conditioning.',connection:'Connect technical milestones to scheduled sessions.'},
];
export const activeFocuses=focusRegistry.filter(f=>f.status==='active');
export const comingSoonFocuses=focusRegistry.filter(f=>f.status==='coming-soon');
