import {useState} from 'react';
import {ArrowLeft,Check,Plus,Search,Minus} from 'lucide-react';
import {focusRegistry,type FocusId} from './focusRegistry';
type Props={enabled:FocusId[];onAdd:(id:FocusId)=>void;onRemove:(id:FocusId)=>void;onOpen:(id:FocusId)=>void;onBack:()=>void};
export default function FocusCatalog({enabled,onAdd,onRemove,onOpen,onBack}:Props){
 const[selected,setSelected]=useState<FocusId|null>(null);
 const[query,setQuery]=useState('');
 const[confirmRemove,setConfirmRemove]=useState<FocusId|null>(null);
 const chosen=focusRegistry.find(f=>f.id===selected);
 const matches=focusRegistry.filter(f=>(f.name+' '+f.description).toLowerCase().includes(query.toLowerCase()));
 return <section className="arc-focus-catalog">
 <header className="arc-page-header"><button className="arc-focus-back" type="button" onClick={onBack}><ArrowLeft size={16}/> Back</button><span className="eyebrow">EXPLORE ARC</span><h1>Manage your focuses</h1><p>A focus is an area of your active life you want to develop. Explore what each one could become in Arc.</p></header>
 <div className="arc-focus-catalog-layout"><div className="arc-focus-catalog-list"><label className="arc-focus-search"><Search size={16}/><input aria-label="Search focuses" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search activities"/></label><div className="arc-focus-catalog-buttons">{matches.map(f=>{const Icon=f.icon;return <button type="button" key={f.id} className={selected===f.id?'selected':''} onClick={()=>{setSelected(f.id);setConfirmRemove(null)}}><Icon size={18}/><span><strong>{f.name}</strong><small>{enabled.includes(f.id)?'Added':f.status==='active'?'Available now':'Preview focus'}</small></span>{enabled.includes(f.id)&&<Check size={16}/>}</button>})}</div>{!matches.length&&<p>No matching focuses.</p>}</div>
 <div className="arc-focus-catalog-detail">{chosen? <><div className="arc-focus-detail-heading"><chosen.icon size={26}/><div><span className="eyebrow">FOCUS CONCEPT</span><h2>{chosen.name}</h2></div></div><p className="arc-focus-lede">{chosen.concept??chosen.description}</p><h3>What you could track</h3><p>{chosen.track??'Practice sessions, time invested and progress toward meaningful goals.'}</p><h3>How it fits into Arc</h3><p>{chosen.connection??'Set a goal, plan activity on Calendar, act through Today and review progress over time.'}</p>{chosen.status==='coming-soon'&&<p className="arc-focus-preview-note">Preview focus: adding this creates a sidebar destination and concept page. Dedicated tracking tools are not available yet.</p>}<div className="arc-focus-detail-actions">{!enabled.includes(chosen.id)?<button className="primary" type="button" onClick={()=>onAdd(chosen.id)}><Plus size={16}/> Add {chosen.shortName}</button>:<><button className="primary" type="button" onClick={()=>onOpen(chosen.id)}>Open {chosen.shortName}</button>{chosen.status==='coming-soon'&&<button className="arc-focus-remove" type="button" onClick={()=>setConfirmRemove(chosen.id)}><Minus size={16}/> Remove from sidebar</button>}</>}</div>{confirmRemove===chosen.id&&<div className="arc-focus-confirm" role="group" aria-label="Confirm remove focus"><p>Hide {chosen.name} from your sidebar? This does not delete goals, activities or history.</p><button type="button" onClick={()=>{onRemove(chosen.id);setConfirmRemove(null)}}>Confirm remove</button><button type="button" onClick={()=>setConfirmRemove(null)}>Cancel</button></div>}</>:<div className="arc-focus-empty"><span className="eyebrow">CHOOSE YOUR NEXT DIRECTION</span><h2>What would you like to explore?</h2><p>Select any focus on the left to learn what it involves, which metrics might matter and how it could support your goals.</p></div>}</div></div></section>;
}
