import{CalendarDays,CheckCircle2,Plus,Target}from'lucide-react';
import type{PlannedActivity}from'../plans';
import{uniqueActivities}from'./uniqueActivities';
const iso=(d:Date)=>[d.getFullYear(),String(d.getMonth()+1).padStart(2,'0'),String(d.getDate()).padStart(2,'0')].join('-');
const timeLabel=(value?:string)=>{if(!value)return'';const [h,m]=value.split(':').map(Number);if(!Number.isFinite(h)||!Number.isFinite(m))return value;const d=new Date();d.setHours(h,m);return d.toLocaleTimeString([],{hour:'numeric',minute:'2-digit'})};
export default function TodayGlance({plans,onOpenCalendar}:{plans:PlannedActivity[];onOpenCalendar:()=>void}){
 const today=iso(new Date()),sessions=uniqueActivities(plans).filter(p=>p.date===today),completed=sessions.filter(p=>p.status==='Completed'),pending=sessions.filter(p=>p.status==='Planned'),total=completed.length+pending.length;
 const next=pending.slice().sort((a,b)=>(a.time??'99:99').localeCompare(b.time??'99:99'))[0],percent=total?Math.round(completed.length/total*100):0;
 return <section className="arc-today-glance" aria-label="Today's plan summary"><div className="arc-glance-heading"><span className="eyebrow">YOUR DAY</span><h2>Today's plan</h2></div><div className="arc-glance-count"><strong>{completed.length}<span> / {total}</span></strong><small>activities completed</small></div><div className="arc-glance-progress" role="progressbar" aria-label="Today's completion" aria-valuemin={0} aria-valuemax={100} aria-valuenow={percent}><span style={{width:percent+'%'}}/></div>{next?<div className="arc-glance-next"><span className="eyebrow">NEXT ACTIVITY</span><b>{next.title}</b><small>{[timeLabel(next.time),next.durationMinutes?next.durationMinutes+' min':''].filter(Boolean).join(' · ')||'Not timed'}</small></div>:<p className="arc-glance-message">{total?'All planned activities completed.':'Nothing planned today.'}</p>}<button className="arc-glance-action" type="button" onClick={onOpenCalendar}>{total?<><CalendarDays size={14}/>Open Calendar</>:<><Plus size={14}/>Add activity</>}</button>{pending.length>0&&<small className="arc-glance-remaining"><Target size={13}/>{pending.length} remaining today</small>}{total>0&&completed.length===total&&<small className="arc-glance-remaining"><CheckCircle2 size={13}/>Daily plan complete</small>}</section>;
}
