import{trainingIntelligence}from'./trainingIntelligence';
import type{Goal}from'../goals';import type{PlannedActivity}from'../plans';import type{DailyState}from'./dailyState';import type{StateObservation}from'./stateHistory';
type Props={plans:PlannedActivity[];goals:Goal[];states?:DailyState[];history?:StateObservation[];compact?:boolean};
const localToday=()=>{const d=new Date();return d.getFullYear()+'-'+String(d.getMonth()+1).padStart(2,'0')+'-'+String(d.getDate()).padStart(2,'0')};
export default function TrainingIntelligencePanel({plans,goals,states=[],history=[],compact=false}:Props){
 const data=trainingIntelligence(plans,goals,localToday(),states,history);
 if(compact)return <section className="arc-intelligence-compact" aria-label="Training intelligence"><span className="eyebrow">TRAINING INSIGHT</span><p>{data.insight}</p><small>{data.completedSessions} completed sessions in 7 days · {data.actualMinutes} measured minutes{data.measuredSessions<data.completedSessions?' · Actual duration missing for '+(data.completedSessions-data.measuredSessions):''}</small></section>;
 return <section className="builder-card arc-intelligence-panel" aria-label="Training intelligence"><span className="eyebrow">TRAINING INTELLIGENCE · 7 DAYS</span><h2>Training, recovery &amp; goal alignment</h2><div className="arc-intelligence-grid"><article><span>TRAINING</span><b>{data.completedSessions} completed</b><small>{data.plannedMinutes} min scheduled in past 7 days · {data.actualMinutes} min measured ({data.measuredSessions}/{data.completedSessions} completed sessions)</small></article><article><span>EFFORT LOAD</span><b>{data.loadSessions?Math.round(data.measuredLoad):'—'}</b><small>Actual minutes × effort (RPE) · {data.loadSessions} sessions with both inputs; not a recovery score</small></article><article><span>GOAL ALIGNMENT</span><b>{data.linkedSessions}/{data.completedSessions}</b><small>Completed sessions linked to an active goal · {data.gaps.length} supporting activity gap(s) this calendar week</small></article><article><span>RECOVERY CONTEXT</span><b>{data.recovery.warnings.length} caution(s)</b><small>{data.recovery.warnings[0]??'No recorded cautions'}{data.recovery.missing.length?' · Missing: '+data.recovery.missing.join('; '):''}</small></article></div><div className="arc-intelligence-details"><div><h3>Goal support still needed</h3>{data.gaps.length?data.gaps.slice(0,5).map((g,i)=><p key={i}>{g.goal}: {g.missing} × {g.type}</p>):<p>No outstanding tracked support gaps this week.</p>}</div><div><h3>Next seven days</h3>{data.upcoming.length?data.upcoming.slice(0,6).map(p=><p key={p.id}>{p.date} {p.time??'Time unset'} · {p.title}</p>):<p>No upcoming Calendar sessions recorded.</p>}</div></div></section>;
}
