export type TechniqueStatus='Learning'|'Drilling'|'Usable'|'Reliable'|'A-Game';
export type BjjTechnique={id:string;name:string;position:string;category:string;applicability:('Gi'|'No-Gi')[];status:TechniqueStatus;tags:string[];setup:string;steps:string[];cues:string[];mistakes:string[];followUps:string[];notes:string;videoUrl?:string};
export const BJJ_TECHNIQUES_KEY='workoutapp.bjj-techniques.v1';
export const techniqueStatuses:TechniqueStatus[]=['Learning','Drilling','Usable','Reliable','A-Game'];
export const starterTechniques:BjjTechnique[]=[
{id:'scissor-sweep',name:'Scissor Sweep',position:'Closed Guard',category:'Sweep',applicability:['Gi','No-Gi'],status:'Reliable',tags:['A-Game','Sweep'],setup:'Break posture and establish upper-body control before opening your guard.',steps:['Control the upper body and create an angle.','Bring the top knee across the torso as a frame.','Drop the lower leg to block the far knee.','Pull the opponent forward while scissoring the legs and turning them over.','Follow the sweep immediately into a stable top position.'],cues:['Angle before power','Keep posture broken','Follow the sweep to top control'],mistakes:['Staying square underneath the opponent','Trying to kick rather than combine upper-body pull and leg action'],followUps:['Mount','Hip Bump Sweep','Kimura'],notes:'A dependable sweep; use this record to capture the grips and timing that work best in live rounds.'},
{id:'side-americana',name:'Americana from Side Control',position:'Side Control Top',category:'Submission',applicability:['Gi','No-Gi'],status:'Reliable',tags:['Submission','A-Game'],setup:'Establish stable side control and isolate the near arm without sacrificing base.',steps:['Pin the wrist to the mat with the same-side hand.','Thread the other arm under the elbow and secure the figure-four grip.','Keep the wrist connected to the mat.','Draw the elbow down while gradually lifting the elbow to finish.'],cues:['Control before submission','Keep the wrist pinned','Do not give away side control chasing the arm'],mistakes:['Lifting the wrist off the mat','Allowing the opponent to turn freely while attacking'],followUps:['Straight Armlock','Armbar','Mount'],notes:'Strong finishing option from a position that is already a strength.'},
{id:'mount-control',name:'Mount Control Cycle',position:'Mount Top',category:'Control',applicability:['Gi','No-Gi'],status:'Learning',tags:['Needs Work','Position'],setup:'Secure mount before attempting a submission.',steps:['Settle hips and establish a wide, reactive base.','Win inside arm position and control the head/shoulder line.','Climb the knees as space opens.','Use grapevines, crossface, or technical mount based on the escape response.','Attack only after the opponent is carrying your weight and their elbows separate.'],cues:['Position before submission','Climb the mount','Make them move first'],mistakes:['Attacking too early','Sitting upright without controlling the upper body','Failing to follow elbow-knee escape movement'],followUps:['Technical Mount','Americana','Arm Triangle','Mounted Armbar'],notes:'Development area: convert getting to mount into sustained control and predictable attacks.'},
{id:'knee-pick',name:'Underhook Knee Pick',position:'Standing',category:'Takedown',applicability:['Gi','No-Gi'],status:'Usable',tags:['Stand-up','Competition'],setup:'Right leg forward; establish head position and right-side underhook/body connection.',steps:['Win inside head position and the underhook.','Connect to the body and pressure the opponent off balance.','Drive the head while reaching the near knee.','Pick the knee as the upper body is driven in the opposite direction.','Follow immediately into top control.'],cues:['Head drives the finish','Move the upper body before taking the knee','Stay connected on the landing'],mistakes:['Reaching for the leg before creating an upper-body reaction','Losing head position'],followUps:['Body Lock Trip','Wrestle-Up','Side Control'],notes:'Part of the current standing system.'}
];
