import {useState} from 'react';
import type {PlannedActivity} from './plans';
import type {ActivityActuals} from './arc/activityActuals';
export type EditableActivity=PlannedActivity & {actuals?:ActivityActuals};
export default function CalendarActivityEditor({activity,onSave,onClose}:{activity:EditableActivity;onSave:(a:EditableActivity)=>void;onClose:()=>void}){
const [draft,setDraft]=useState(activity);
const [actuals,setActuals]=useState<ActivityActuals>(activity.actuals??{});
const change=(field:keyof ActivityActuals,value:string)=>setActuals(a=>({...a,[field]:value===''?undefined:Number(value)}));
const metric=(label:string,field:keyof ActivityActuals,max?:number)=><label>{label}<input type="number" min="0" max={max} value={typeof actuals[field]==='number'?actuals[field] as number:''} onChange={e=>change(field,e.target.value)}/></label>;
return <div className="arc-activity-overlay" onClick={onClose}><section className="arc-activity-editor" role="dialog" aria-modal="true" aria-label="Edit activity" onClick={e=>e.stopPropagation()}><h2>Edit activity</h2><label>Title<input value={draft.title} onChange={e=>setDraft({...draft,title:e.target.value})}/></label><label>Date<input type="date" value={draft.date} onChange={e=>setDraft({...draft,date:e.target.value})}/></label><label>Time<input type="time" value={draft.time??""} onChange={e=>setDraft({...draft,time:e.target.value})}/></label><label>Type<select value={draft.type} onChange={e=>setDraft({...draft,type:e.target.value as PlannedActivity['type']})}>{['Strength','BJJ','Cardio','Mobility','Recovery','Other'].map(t=><option key={t}>{t}</option>)}</select></label><label>Planned minutes<input type="number" min="0" value={draft.durationMinutes??''} onChange={e=>setDraft({...draft,durationMinutes:e.target.value===''?undefined:Number(e.target.value)})}/></label><label>Status<select value={draft.status} onChange={e=>setDraft({...draft,status:e.target.value as PlannedActivity['status']})}>{['Planned','Completed','Skipped'].map(t=><option key={t}>{t}</option>)}</select></label><h3>Session overview</h3><div className="arc-session-overview"><span>Planned <b>{draft.durationMinutes===undefined?'Not set':draft.durationMinutes+' min'}</b></span><span>Actual <b>{actuals.actualDurationMinutes===undefined?'Not recorded':actuals.actualDurationMinutes+' min'}</b></span><span>Difference <b>{actuals.actualDurationMinutes===undefined||draft.durationMinutes===undefined?'—':(actuals.actualDurationMinutes-draft.durationMinutes>0?'+':'')+(actuals.actualDurationMinutes-draft.durationMinutes)+' min'}</b></span></div><h3>Actual session</h3><p className="arc-activity-hint">Planned minutes are not actual training time. BJJ hours and training load require actual minutes; RPE can be recorded independently.</p>{metric('Actual minutes','actualDurationMinutes')}{metric('Effort / RPE (1–10)','effort',10)}{draft.type==='BJJ'&&<>{metric('Rounds','rounds')}{metric('Live minutes','liveMinutes')}{metric('Submissions for','submissionsFor')}{metric('Submissions against','submissionsAgainst')}<label>Techniques<textarea value={actuals.techniques??''} onChange={e=>setActuals({...actuals,techniques:e.target.value})}/></label></>}{draft.type==='Cardio'&&<>{metric('Distance (km)','distanceKm')}{metric('Elevation gain (m)','elevationMeters')}</>}<label>Recovery / how you felt<textarea value={actuals.recoveryNote??''} onChange={e=>setActuals({...actuals,recoveryNote:e.target.value})}/></label><label>Notes<textarea value={draft.notes??''} onChange={e=>setDraft({...draft,notes:e.target.value})}/></label><button onClick={onClose}>Cancel</button><button className="primary" disabled={!draft.title.trim()||!draft.date||(actuals.effort!==undefined&&(actuals.effort<1||actuals.effort>10))} onClick={()=>onSave({...draft,actuals})}>Save activity</button></section></div>;
}
