import{exercises}from'./data';import{DayType,defaultProgression,defaultPrescription,exerciseFitsDay,exerciseFitsGoal,Program,schemaForGoal,WorkoutDay}from'./programs';
export type Split='Auto'|'Full Body'|'Upper / Lower'|'Push / Pull / Legs'|'Mobility / Flexibility';
export type GeneratorConfig={goal:Program['goal'];weeks:number;daysPerWeek:number;split:Split;sessionMinutes:number;equipment:string[];mobility:'None'|'Warm-up'|'Cooldown'|'Dedicated';bjjDays?:number[]};
const uid=()=>crypto.randomUUID();
const dayTypes=(c:GeneratorConfig):DayType[]=>{if(c.goal==='Mobility')return Array(c.daysPerWeek).fill('Mobility');if(c.goal==='Flexibility')return Array(c.daysPerWeek).fill('Stretching');if(c.goal==='Recovery')return Array(c.daysPerWeek).fill('Recovery');let split=c.split;if(split==='Auto')split=c.daysPerWeek<=3?'Full Body':c.daysPerWeek===4?'Upper / Lower':'Push / Pull / Legs';if(split==='Full Body')return Array(c.daysPerWeek).fill('Full Body');if(split==='Upper / Lower')return Array.from({length:c.daysPerWeek},(_,i)=>i%2===0?'Upper Body':'Lower Body') as DayType[];if(split==='Push / Pull / Legs'){const a:DayType[]=['Push','Pull','Legs'];return Array.from({length:c.daysPerWeek},(_,i)=>a[i%3])}if(split==='Mobility / Flexibility')return Array.from({length:c.daysPerWeek},(_,i)=>i%2===0?'Mobility':'Stretching') as DayType[];return Array(c.daysPerWeek).fill('Full Body')};
export function suggestStrengthDays(count:number,bjjDays:number[]=[]){const all=[0,1,2,3,4,5,6],chosen:number[]=[];while(chosen.length<Math.min(count,7)){const ranked=all.filter(d=>!chosen.includes(d)).sort((a,b)=>{const score=(d:number)=>{const prev=(d+6)%7,next=(d+1)%7;return(bjjDays.includes(d)?100:0)+(bjjDays.includes(prev)?3:0)+(bjjDays.includes(next)?3:0)+chosen.reduce((n,x)=>n+(Math.min((d-x+7)%7,(x-d+7)%7)<=1?2:0),0)};return score(a)-score(b)||a-b});chosen.push(ranked[0])}return chosen};
const targetCount=(minutes:number,type:DayType)=>type==='Mobility'||type==='Stretching'||type==='Recovery'?Math.max(4,Math.min(8,Math.round(minutes/10))):Math.max(3,Math.min(8,Math.round(minutes/12)));
const score=(e:(typeof exercises)[number],goal:Program['goal'],type:DayType)=>{let s=0;if(e.goals.includes(goal as never))s+=5;if(type==='Upper Body'&&e.group==='Upper Body')s+=3;if((type==='Lower Body'||type==='Legs')&&e.group==='Legs')s+=3;if(type==='Arms'&&e.group==='Arms')s+=4;if(/Squat|Press|Pull|Row|Hinge/i.test(e.movement))s+=2;return s};
export function generateProgram(c:GeneratorConfig,startDate?:string):Program{const types=dayTypes(c);const days:WorkoutDay[]=types.map((type,i)=>{let pool=exercises.filter(e=>exerciseFitsGoal(e,c.goal)&&exerciseFitsDay(e,type)&&(c.equipment.length===0||c.equipment.includes(e.equipment)));if(!pool.length)pool=exercises.filter(e=>exerciseFitsGoal(e,c.goal)&&exerciseFitsDay(e,type));pool=[...pool].sort((a,b)=>score(b,c.goal,type)-score(a,c.goal,type));const chosen=pool.slice(0,targetCount(c.sessionMinutes,type));const prescriptions=chosen.map(e=>({id:uid(),exerciseId:e.id,...defaultPrescription(c.goal,e.category,e.defaultUnit==='seconds')}));const suffix=types.filter(x=>x===type).length>1?` ${String.fromCharCode(65+types.slice(0,i+1).filter(x=>x===type).length-1)}`:'';return{id:uid(),name:`${type}${suffix}`,type,prescriptions}});if(c.mobility!=='None'&&!['Mobility','Flexibility','Recovery'].includes(c.goal)&&c.mobility==='Dedicated'){const type:DayType='Mobility';const pool=exercises.filter(e=>e.category==='Mobility').slice(0,targetCount(c.sessionMinutes,type));days.push({id:uid(),name:'Mobility',type,prescriptions:pool.map(e=>({id:uid(),exerciseId:e.id,...defaultPrescription('Mobility',e.category,e.defaultUnit==='seconds')}))})}const endDate=startDate?(()=>{const[y,m,d]=startDate.split('-').map(Number),x=new Date(Date.UTC(y,m-1,d));x.setUTCDate(x.getUTCDate()+c.weeks*7);return x.toISOString().slice(0,10)})():undefined;return{id:uid(),name:`${c.weeks}-Week ${c.goal} Block`,goal:c.goal,weeks:c.weeks,activeWeek:1,activeDayId:days[0].id,days,progression:{...defaultProgression,type:schemaForGoal(c.goal)},status:'Draft',createdAt:new Date().toISOString(),startDate,endDate}}
