import type{Program}from'./programs';export type LibraryProgram={id:string;name:string;creator:string;goal:string;weeks:number;daysPerWeek:number;level:string;focus:string;description:string;sourceLabel:string;sourceUrl:string;implementation:'Publicly documented'|'Framework'|'WorkoutApp adaptation';template?:'smolov-jr'|'texas-method'|'hatch'};export const programLibrary:LibraryProgram[]=[
{id:'smolov-jr',name:'Smolov Jr.',creator:'Sergey Smolov tradition',goal:'Strength',weeks:3,daysPerWeek:4,level:'Advanced',focus:'Squat or bench specialization',description:'High-frequency specialization: 6×6, 7×5, 8×4 and 10×3 across four weekly sessions.',sourceLabel:'Smolov Jr. published protocol',sourceUrl:'https://www.smolovjr.com/smolov-squat-program/',implementation:'Publicly documented',template:'smolov-jr'},
{id:'hatch',name:'Hatch Squat Program',creator:'Gayle Hatch',goal:'Strength',weeks:12,daysPerWeek:2,level:'Intermediate / Advanced',focus:'Back squat + front squat',description:'Twelve-week squat specialization built around twice-weekly back- and front-squat work with percentage-based loading.',sourceLabel:'Published Hatch program overview',sourceUrl:'https://liftvault.com/programs/lift-specific/page/2/',implementation:'Framework',template:'hatch'},
{id:'texas',name:'Texas Method',creator:'Mark Rippetoe / Glenn Pendlay',goal:'Strength',weeks:8,daysPerWeek:3,level:'Intermediate',focus:'Weekly strength progression',description:'Volume, recovery and intensity sessions organize stress across the training week.',sourceLabel:'Starting Strength — The Texas Method',sourceUrl:'https://startingstrength.com/article/programming/the_texas_method',implementation:'Framework',template:'texas-method'},
{id:'gzcl',name:'GZCL Method',creator:'Cody Lefever',goal:'Strength',weeks:8,daysPerWeek:4,level:'Intermediate',focus:'Tiered strength and volume',description:'A tier-based framework separating primary strength work, secondary volume and assistance.',sourceLabel:'Publicly described method',sourceUrl:'',implementation:'Framework'},
{id:'531',name:'5/3/1-style Progression',creator:'Jim Wendler',goal:'Strength',weeks:4,daysPerWeek:4,level:'Intermediate',focus:'Long-term main-lift progression',description:'WorkoutApp-compatible framework inspired by publicly described submaximal training-max progression; not a reproduction of paid templates.',sourceLabel:'Creator-authored books recommended for exact templates',sourceUrl:'',implementation:'WorkoutApp adaptation'},
{id:'russian-squat',name:'Russian Squat Routine',creator:'Classic routine',goal:'Strength',weeks:6,daysPerWeek:3,level:'Intermediate / Advanced',focus:'Squat specialization',description:'High-frequency squat progression alternating volume accumulation and increasing intensity.',sourceLabel:'Publicly documented routine',sourceUrl:'',implementation:'Framework'},
{id:'phul',name:'PHUL',creator:'Public training template',goal:'Hypertrophy',weeks:8,daysPerWeek:4,level:'Intermediate',focus:'Power + hypertrophy upper/lower',description:'Four-day upper/lower structure separating power-oriented and hypertrophy-oriented sessions.',sourceLabel:'Publicly described template',sourceUrl:'',implementation:'Framework'},
{id:'gvt',name:'German Volume Training',creator:'Traditional method',goal:'Hypertrophy',weeks:6,daysPerWeek:3,level:'Intermediate',focus:'High-volume hypertrophy',description:'High-volume training centered on repeated sets of a primary movement with limited assistance.',sourceLabel:'Widely published training method',sourceUrl:'',implementation:'Framework'},
{id:'upper-lower',name:'Upper / Lower Strength',creator:'WorkoutApp',goal:'Strength',weeks:8,daysPerWeek:4,level:'Beginner / Intermediate',focus:'General strength',description:'Balanced four-day upper/lower strength block with progressive loading.',sourceLabel:'WorkoutApp original',sourceUrl:'',implementation:'WorkoutApp adaptation'},
{id:'ppl-hypertrophy',name:'Push / Pull / Legs Hypertrophy',creator:'WorkoutApp',goal:'Hypertrophy',weeks:8,daysPerWeek:6,level:'Intermediate',focus:'Muscle growth',description:'Six-day PPL structure for higher-frequency hypertrophy training.',sourceLabel:'WorkoutApp original',sourceUrl:'',implementation:'WorkoutApp adaptation'},
{id:'bjj-strength',name:'BJJ Strength — 3 Day',creator:'WorkoutApp',goal:'Strength',weeks:8,daysPerWeek:3,level:'All levels',focus:'Strength alongside mat training',description:'Lower-volume full-body strength designed to coexist with frequent grappling.',sourceLabel:'WorkoutApp original',sourceUrl:'',implementation:'WorkoutApp adaptation'},
{id:'bjj-comp',name:'BJJ Competition Strength Taper',creator:'WorkoutApp',goal:'Strength',weeks:6,daysPerWeek:2,level:'Intermediate',focus:'Competition preparation',description:'Two-day strength maintenance block intended to reduce gym fatigue as competition approaches.',sourceLabel:'WorkoutApp original',sourceUrl:'',implementation:'WorkoutApp adaptation'}];
const id=()=>crypto.randomUUID();export function instantiateLibraryProgram(x:LibraryProgram):Program{const mk=(name:string,sets:number,reps:number,weight=0)=>({id:id(),exerciseId:'back-squat',sets,minReps:reps,maxReps:reps,rir:2,weight}),days=x.template==='smolov-jr'?[['Day 1 · 6×6',6,6],['Day 2 · 7×5',7,5],['Day 3 · 8×4',8,4],['Day 4 · 10×3',10,3]].map(([n,s,r])=>({id:id(),name:String(n),type:'Lower Body' as const,prescriptions:[mk(String(n),Number(s),Number(r))]})):x.template==='texas-method'?[['Volume',5,5],['Recovery',2,5],['Intensity',1,5]].map(([n,s,r])=>({id:id(),name:String(n),type:'Full Body' as const,prescriptions:[mk(String(n),Number(s),Number(r))]})):[{id:id(),name:x.template==='hatch'?'Squat Day A':'Day 1',type:'Full Body' as const,prescriptions:[mk('Main lift',4,6)]},{id:id(),name:x.template==='hatch'?'Squat Day B':'Day 2',type:'Full Body' as const,prescriptions:[mk('Main lift',4,5)]}];return{id:id(),name:x.name,goal:x.goal==='Hypertrophy'?'Hypertrophy':'Strength',weeks:x.weeks,activeWeek:1,activeDayId:days[0].id,days,progression:{type:x.template==='smolov-jr'?'Linear Load':'Linear Periodization',loadStep:5,startRir:3,endRir:1,deloadEvery:0,deloadPercent:15},status:'Draft',createdAt:new Date().toISOString()}}
