import type{Program}from'./programs';export type LibraryProgram={id:string;name:string;creator:string;goal:string;weeks:number;daysPerWeek:number;level:string;focus:string;description:string;sourceLabel:string;sourceUrl:string;implementation:'Publicly documented'|'Framework'|'WorkoutApp adaptation';template?:'smolov-jr'|'texas-method'|'hatch';split?:'full'|'upper-lower'|'ppl'|'mobility'|'recovery'};export const programLibrary:LibraryProgram[]=[
{id:'smolov-jr',name:'Smolov Jr.',creator:'Sergey Smolov tradition',goal:'Strength',weeks:3,daysPerWeek:4,level:'Advanced',focus:'Squat or bench specialization',description:'High-frequency specialization: 6×6, 7×5, 8×4 and 10×3 across four weekly sessions.',sourceLabel:'Smolov Jr. published protocol',sourceUrl:'https://www.smolovjr.com/smolov-squat-program/',implementation:'Publicly documented',template:'smolov-jr'},
{id:'hatch',name:'Hatch Squat Program',creator:'Gayle Hatch',goal:'Strength',weeks:12,daysPerWeek:2,level:'Intermediate / Advanced',focus:'Back squat + front squat',description:'Twelve-week squat specialization built around twice-weekly back- and front-squat work with percentage-based loading.',sourceLabel:'Published Hatch program overview',sourceUrl:'https://liftvault.com/programs/lift-specific/page/2/',implementation:'Framework',template:'hatch'},
{id:'texas',name:'Texas Method',creator:'Mark Rippetoe / Glenn Pendlay',goal:'Strength',weeks:8,daysPerWeek:3,level:'Intermediate',focus:'Weekly strength progression',description:'Volume, recovery and intensity sessions organize stress across the training week.',sourceLabel:'Starting Strength — The Texas Method',sourceUrl:'https://startingstrength.com/article/programming/the_texas_method',implementation:'Framework',template:'texas-method'},
{id:'gzcl',name:'GZCL Method',creator:'Cody Lefever',goal:'Strength',weeks:8,daysPerWeek:4,level:'Intermediate',focus:'Tiered strength and volume',description:'A tier-based framework separating primary strength work, secondary volume and assistance.',sourceLabel:'Publicly described method',sourceUrl:'',implementation:'Framework'},
{id:'531',name:'5/3/1-style Progression',creator:'Jim Wendler',goal:'Strength',weeks:4,daysPerWeek:4,level:'Intermediate',focus:'Long-term main-lift progression',description:'WorkoutApp-compatible framework inspired by publicly described submaximal training-max progression; not a reproduction of paid templates.',sourceLabel:'Creator-authored books recommended for exact templates',sourceUrl:'',implementation:'WorkoutApp adaptation'},
{id:'russian-squat',name:'Russian Squat Routine',creator:'Classic routine',goal:'Strength',weeks:6,daysPerWeek:3,level:'Intermediate / Advanced',focus:'Squat specialization',description:'High-frequency squat progression alternating volume accumulation and increasing intensity.',sourceLabel:'Publicly documented routine',sourceUrl:'',implementation:'Framework'},
{id:'phul',name:'PHUL',creator:'Public training template',goal:'Hypertrophy',weeks:8,daysPerWeek:4,level:'Intermediate',focus:'Power + hypertrophy upper/lower',description:'Four-day upper/lower structure separating power-oriented and hypertrophy-oriented sessions.',sourceLabel:'Publicly described template',sourceUrl:'',implementation:'Framework'},
{id:'gvt',name:'German Volume Training',creator:'Traditional method',goal:'Hypertrophy',weeks:6,daysPerWeek:3,level:'Intermediate',focus:'High-volume hypertrophy',description:'High-volume training centered on repeated sets of a primary movement with limited assistance.',sourceLabel:'Widely published training method',sourceUrl:'',implementation:'Framework'},
{id:'upper-lower',name:'Upper / Lower Strength',creator:'WorkoutApp',goal:'Strength',weeks:8,daysPerWeek:4,level:'Beginner / Intermediate',focus:'General strength',description:'Balanced four-day upper/lower strength block with progressive loading.',sourceLabel:'WorkoutApp original',sourceUrl:'',implementation:'WorkoutApp adaptation'},
{id:'ppl-hypertrophy',name:'Push / Pull / Legs Hypertrophy',creator:'WorkoutApp',goal:'Hypertrophy',weeks:8,daysPerWeek:6,level:'Intermediate',focus:'Muscle growth',description:'Six-day PPL structure for higher-frequency hypertrophy training.',sourceLabel:'WorkoutApp original',sourceUrl:'',implementation:'WorkoutApp adaptation'},
{id:'bjj-strength',name:'BJJ Strength — 3 Day',creator:'WorkoutApp',goal:'Strength',weeks:8,daysPerWeek:3,level:'All levels',focus:'Strength alongside mat training',description:'Lower-volume full-body strength designed to coexist with frequent grappling.',sourceLabel:'WorkoutApp original',sourceUrl:'',implementation:'WorkoutApp adaptation'},
{id:'bjj-comp',name:'BJJ Competition Strength Taper',creator:'WorkoutApp',goal:'Strength',weeks:6,daysPerWeek:2,level:'Intermediate',focus:'Competition preparation',description:'Two-day strength maintenance block intended to reduce gym fatigue as competition approaches.',sourceLabel:'WorkoutApp original',sourceUrl:'',implementation:'WorkoutApp adaptation'},
{id:'novice-3',name:'Novice Full Body — 3 Day',creator:'WorkoutApp',goal:'Strength',weeks:8,daysPerWeek:3,level:'Beginner',focus:'Foundational strength',description:'Simple three-day full-body progression emphasizing squat, press, pull and hinge patterns.',sourceLabel:'WorkoutApp original',sourceUrl:'',implementation:'WorkoutApp adaptation',split:'full'},
{id:'strength-2',name:'Minimal Strength — 2 Day',creator:'WorkoutApp',goal:'Strength',weeks:8,daysPerWeek:2,level:'All levels',focus:'Low-frequency strength',description:'Two efficient full-body sessions for busy schedules or high sport volume.',sourceLabel:'WorkoutApp original',sourceUrl:'',implementation:'WorkoutApp adaptation',split:'full'},
{id:'ppl-3',name:'Push / Pull / Legs — 3 Day',creator:'WorkoutApp',goal:'Hypertrophy',weeks:8,daysPerWeek:3,level:'Beginner / Intermediate',focus:'Moderate-frequency hypertrophy',description:'One push, pull and leg session each week.',sourceLabel:'WorkoutApp original',sourceUrl:'',implementation:'WorkoutApp adaptation',split:'ppl'},
{id:'ul-hypertrophy',name:'Upper / Lower Hypertrophy — 4 Day',creator:'WorkoutApp',goal:'Hypertrophy',weeks:8,daysPerWeek:4,level:'Intermediate',focus:'Balanced muscle growth',description:'Four-day upper/lower hypertrophy block with repeat exposure.',sourceLabel:'WorkoutApp original',sourceUrl:'',implementation:'WorkoutApp adaptation',split:'upper-lower'},
{id:'bjj-minimal',name:'BJJ Strength — 2 Day Minimal',creator:'WorkoutApp',goal:'Strength',weeks:8,daysPerWeek:2,level:'All levels',focus:'Strength with high mat volume',description:'Two low-volume full-body sessions designed to preserve recovery for frequent BJJ.',sourceLabel:'WorkoutApp original',sourceUrl:'',implementation:'WorkoutApp adaptation',split:'full'},
{id:'bjj-inseason',name:'BJJ In-Season Maintenance',creator:'WorkoutApp',goal:'Strength',weeks:8,daysPerWeek:2,level:'Intermediate',focus:'Maintain strength during hard BJJ weeks',description:'Low-volume strength maintenance for periods when BJJ is the primary training stress.',sourceLabel:'WorkoutApp original',sourceUrl:'',implementation:'WorkoutApp adaptation',split:'full'},
{id:'bjj-offseason',name:'BJJ Off-Season Strength',creator:'WorkoutApp',goal:'Strength',weeks:10,daysPerWeek:3,level:'Intermediate',focus:'Build strength between competitions',description:'Three-day block allowing more strength volume when competition-specific fatigue is lower.',sourceLabel:'WorkoutApp original',sourceUrl:'',implementation:'WorkoutApp adaptation',split:'full'},
{id:'mixed-athlete',name:'Hybrid Athlete — 3 Day',creator:'WorkoutApp',goal:'Mixed',weeks:8,daysPerWeek:3,level:'Intermediate',focus:'Strength + work capacity',description:'Full-body resistance training balanced for athletes with conditioning or sport practice.',sourceLabel:'WorkoutApp original',sourceUrl:'',implementation:'WorkoutApp adaptation',split:'full'},
{id:'mobility-daily',name:'Daily Mobility — 15 Minute',creator:'WorkoutApp',goal:'Mobility',weeks:6,daysPerWeek:6,level:'All levels',focus:'Daily movement quality',description:'Short recurring mobility sessions for hips, shoulders, ankles and thoracic spine.',sourceLabel:'WorkoutApp original',sourceUrl:'',implementation:'WorkoutApp adaptation',split:'mobility'},
{id:'mobility-bjj',name:'BJJ Mobility — 3 Day',creator:'WorkoutApp',goal:'Mobility',weeks:6,daysPerWeek:3,level:'All levels',focus:'Grappling mobility',description:'Hip rotation, adductors, ankles, thoracic spine and shoulders for grapplers.',sourceLabel:'WorkoutApp original',sourceUrl:'',implementation:'WorkoutApp adaptation',split:'mobility'},
{id:'flexibility-3',name:'Flexibility — 3 Day',creator:'WorkoutApp',goal:'Flexibility',weeks:8,daysPerWeek:3,level:'All levels',focus:'Progressive flexibility',description:'Three weekly stretching sessions with progressive hold duration.',sourceLabel:'WorkoutApp original',sourceUrl:'',implementation:'WorkoutApp adaptation',split:'mobility'},
{id:'recovery-2',name:'Recovery Reset — 2 Day',creator:'WorkoutApp',goal:'Recovery',weeks:6,daysPerWeek:2,level:'All levels',focus:'Low-stress recovery',description:'Easy mobility and stretching sessions intended for recovery days.',sourceLabel:'WorkoutApp original',sourceUrl:'',implementation:'WorkoutApp adaptation',split:'recovery'}
];
const id=()=>crypto.randomUUID();export type ProgramSetup={liftId:string;trainingMax:number;rounding:number;startDate:string;weekdays:number[]};const roundTo=(n:number,step:number)=>step>0?Math.round(n/step)*step:n;
const mkRx=(exerciseId:string,sets:number,reps:number,weight=0,rir=2)=>({id:id(),exerciseId,sets,minReps:reps,maxReps:reps,rir,weight});
const strength=['back-squat','bench','rdl','db-row','pullup','dip'],mobility=['90-90-switch','world-greatest','cat-cow','open-book','wall-slide','ankle-rock','adductor-rockback','hip-cars','shoulder-cars'],stretch=['hamstring-static','quad-static','hip-flexor-kneeling','figure-four','calf-wall','doorway-pec','lat-child-pose','upper-trap-stretch'];
const types=(x:LibraryProgram)=>{if(x.split==='ppl')return Array.from({length:x.daysPerWeek},(_,i)=>['Push','Pull','Legs'][i%3]);if(x.split==='upper-lower')return Array.from({length:x.daysPerWeek},(_,i)=>i%2?'Lower Body':'Upper Body');if(x.split==='mobility')return Array(x.daysPerWeek).fill(x.goal==='Flexibility'?'Stretching':'Mobility');if(x.split==='recovery')return Array(x.daysPerWeek).fill('Recovery');return Array(x.daysPerWeek).fill('Full Body')};
const genericDays=(x:LibraryProgram,setup?:ProgramSetup)=>types(x).map((type,i)=>{let ids=x.goal==='Mobility'?mobility:x.goal==='Flexibility'?stretch:x.goal==='Recovery'?[...mobility.slice(0,3),...stretch.slice(0,3)]:strength;if(type==='Upper Body'||type==='Push'||type==='Pull')ids=ids.filter(v=>['bench','db-row','pullup','dip'].includes(v));if(type==='Lower Body'||type==='Legs')ids=ids.filter(v=>['back-squat','rdl'].includes(v));const count=x.goal==='Strength'?Math.min(4,ids.length):x.goal==='Hypertrophy'?Math.min(5,ids.length):Math.min(6,ids.length),chosen=ids.slice(0,count);return{id:id(),name:type==='Full Body'?'Full Body '+String.fromCharCode(65+i):type+' '+(Math.floor(i/(x.split==='ppl'?3:2))+1),type:type as any,weekday:setup?.weekdays[i]??i,prescriptions:chosen.map((v,j)=>mkRx(v,x.goal==='Strength'?(j<2?4:3):3,x.goal==='Strength'?(j<2?5:8):x.goal==='Hypertrophy'?10:stretch.includes(v)?30:10,0,x.goal==='Strength'?2:3))}});
export function instantiateLibraryProgram(x:LibraryProgram,setup?:ProgramSetup):Program{const lift=setup?.liftId??'back-squat',tm=Math.max(0,setup?.trainingMax??0),rounding=Math.max(0,setup?.rounding??5),mk=(sets:number,reps:number,pct=.7)=>mkRx(lift,sets,reps,tm?roundTo(tm*pct,rounding):0,2);let days:any[];if(x.template==='smolov-jr')days=[[6,6,.7],[7,5,.75],[8,4,.8],[10,3,.85]].map(([s,r,p],i)=>({id:id(),name:'Day '+(i+1)+' · '+s+'×'+r,type:'Lower Body',weekday:setup?.weekdays[i]??i,prescriptions:[mk(s,r,p)]}));else if(x.template==='texas-method')days=[['Volume',5,5,.7],['Recovery',2,5,.6],['Intensity',1,5,.8]].map(([n,s,r,p],i)=>({id:id(),name:String(n),type:'Full Body',weekday:setup?.weekdays[i]??i,prescriptions:[mk(Number(s),Number(r),Number(p))]}));else if(x.template==='hatch')days=[['Squat Day A',4,6,.7],['Squat Day B',4,5,.75]].map(([n,s,r,p],i)=>({id:id(),name:String(n),type:'Lower Body',weekday:setup?.weekdays[i]??i,prescriptions:[mk(Number(s),Number(r),Number(p))]}));else days=genericDays(x,setup);const goal=(['Strength','Hypertrophy','Mixed','Mobility','Flexibility','Recovery'].includes(x.goal)?x.goal:'Mixed') as Program['goal'],progression=goal==='Strength'?'Linear Load':goal==='Hypertrophy'?'RIR Progression':goal==='Mobility'?'Mobility Flow':goal==='Flexibility'?'Flexibility Progression':goal==='Recovery'?'Mobility Flow':'Undulating',endDate=setup?.startDate?(()=>{const d=new Date(setup.startDate+'T12:00:00');d.setDate(d.getDate()+x.weeks*7);return d.toLocaleDateString('en-CA')})():undefined;return{id:id(),name:x.name,goal,weeks:x.weeks,activeWeek:1,activeDayId:days[0].id,days,progression:{type:x.template==='smolov-jr'?'Linear Load':progression,loadStep:5,startRir:3,endRir:1,deloadEvery:goal==='Strength'?4:0,deloadPercent:15},status:'Draft',createdAt:new Date().toISOString(),startDate:setup?.startDate,endDate}}
